name: skincare
description: "A skincare routine all-in-one app"
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.9.0
  image_picker: ^1.1.2
  flutter_layout_grid: ^2.0.8
  dotted_border: ^3.0.1
  flutter_launcher_icons: ^0.14.4
  go_router: ^15.2.4
  file_picker: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  change_app_package_name: ^1.5.0


flutter:
  uses-material-design: true
  default-flavor: production
